### ISSUE TITLE
Odd InputDate behavior

### ISSUE THREAD

**Issue by lxman** [Blazored/FluentValidation#25]
Minimal repro is here:

https://github.com/lxman/InputDateValidationTest

I am not even sure if this falls under the purview of this project, so please pardon me if this belongs somewhere else. That having been said...

If I run the project in its initial state and select a date in the future, things appear to work as I have come to expect.
![image](https://user-images.githubusercontent.com/20031555/83573025-b0023200-a4f8-11ea-8605-16b39defbf98.png)
However, go into Index.razor and comment out line 8, then uncomment line 7. Things become a bit odd.
![image](https://user-images.githubusercontent.com/20031555/83573255-10916f00-a4f9-11ea-82c3-7126aba2b80b.png)
Notice I still receive my error message but now the outline around the input shows a border that would seem to indicate successful validation.
Now, for some more fun, go into DateModelValidator.cs and uncomment lines 12-16.
![image](https://user-images.githubusercontent.com/20031555/83573458-87c70300-a4f9-11ea-934f-15b295cf17c7.png)
I don't even get my message at this point. It looks like that is the auto-generated message from FluentValidation.
You may note that what I am trying to do here is "subclass" the InputDate component so that I can have some styling and other options built in for use at various places in my site. I have used a similar method with InputText and InputSelect, and they are working well. This issue so far only seems to happen with InputDate.

**Comment by chrissainty** [comment]
Hi @lxman, looking at your repo I think the issue is down to how you've implemented your `TestInputDate` component.

When you're creating a component based on `InputBase` you need to provide the markup and an implementation for `TryParseValueFromString`. You've done the latter but in your markup you just reused the `InputDate` component which is itself inheriting from `InputBase`. 

If you change your code to this everything works as expected.

```razor
<input type="date" class="@CssClass" @bind="@CurrentValue" />
```
