### ISSUE TITLE
What is needed to get validation work for nested objects in nested components ?

### ISSUE THREAD

**Issue by joer33304** [Blazored/FluentValidation#52]
My project is complex, so let me abstract the issue I have:

My main form has an EditContext for a Person which has many addresses and each address is rendered in a loop by a sub component.
The issue is that error messages and red border shows up ONLY for failing validations of main form properties, but not for the sub (address) form. However when I use the validation summary, main and sub from error shows correct. So validation is working, just not the graphics for each item on the sub form. ( example <ValidationMessage For="@(() => Item.Street1)" />

I added     <FluentValidationValidator /> to both main and sub form and I pass the context via         [CascadingParameter] to the child form.

I am missing anything or is this a bug ?

**Comment by chrissainty** [comment]
Without seeing an code it's impossible to say what the issue is. If the `ValidationSummary` is showing the correct validation messages then it doesn't sound like an issue with this library.

Just to be clear, we don't handle anything to do with showing the error or success styling, that is all handled by the components and the `EditContext`. We only execute the validation against the model.

**Comment by joer33304** [comment]
I traced it down. In my case had the sub components outside the form and created a new EditContext inside.
